---
apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    istio-injection: enabled
    istio.io/rev: 1-8-1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - image: zhongfox/grpc-server:v1
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 7001
              protocol: TCP
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: debug
spec:
  ports:
    - name: grpc
      port: 7001
      protocol: TCP
  selector:
    app: grpc-server
  type: ClusterIP
---
