---
apiVersion: v1
kind: Namespace
metadata:
  name: debug
  # labels:
  #   istio-injection: enabled
  #   istio.io/rev: 1-8-1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: zhongfox/sc:v1
          imagePullPolicy: Always
          name: client
          env:
          - name: DESTINATIONS
            value: svc1,svc2
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
